---
version: '3.8'
services:
  db:
    image: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${PGPASS}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
     - "postgres"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
networks:
  postgres:
    driver: "bridge"
  consul-bridge:
    external: true
    
volumes:
  postgres_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/postgres_data"
