version: '3.8'
services:
  pg-1:
    image: devsadds/postgresql-repmg-14.1.0:v1.2.0
    hostname: pg-1-{{.Task.ID}}
    environment:
       POSTGRESQL_POSTGRES_PASSWORD: ${PGUSERPASS}
       POSTGRESQL_USERNAME: ${PGUSER}
       POSTGRESQL_PASSWORD: ${PGPASS}
       POSTGRESQL_DATABASE: ${PGDB}
       REPMGR_PASSWORD: ${REPMGRPW}
       REPMGR_PRIMARY_HOST: "pg-1"
       REPMGR_PRIMARY_PORT: "5432"
       REPMGR_PARTNER_NODES: "pg-1,pg-2"
       REPMGR_NODE_NAME: "pg-1"
       REPMGR_NODE_NETWORK_NAME: "pg-1"
       REPMGR_PORT_NUMBER: "5432"
       POSTGRESQL_DATA_DIR: "/bitnami/postgresql/data"
       SERVER_NAME: "convy"
       DISCOVERY_SERVICE_HOST: "consul-prod"
       CONSUL_SERVICE_NAME: "postgres-14-repmgr"
       POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "repmgr,pg_stat_statements"
       POSTGRESQL_MAX_CONNECTIONS: "10"
       REPMGR_NODE_PRIORITY: "100"
    volumes:
      - "pg-1_data:/bitnami/postgresql"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 2048000000 # (this means 2GB)
    networks:
      dev_network:
    stop_grace_period: 180s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 1000
        window: 180s
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.pg-1  == true ]
  pg-2:
    image: devsadds/postgresql-repmg-14.1.0:v1.2.0
    hostname: pg-2-{{.Task.ID}}
    environment:
       POSTGRESQL_POSTGRES_PASSWORD: ${PGUSERPASS}
       POSTGRESQL_USERNAME: ${PGUSER}
       POSTGRESQL_PASSWORD: ${PGPASS}
       POSTGRESQL_DATABASE: ${PGDB}
       REPMGR_PASSWORD: ${REPMGRPW}
       REPMGR_PRIMARY_HOST: "pg-1"
       REPMGR_PRIMARY_PORT: "5432"
       REPMGR_PARTNER_NODES: "pg-1,pg-2,pg-3"
       REPMGR_NODE_NAME: "pg-2"
       REPMGR_NODE_NETWORK_NAME: "pg-2"
       REPMGR_PORT_NUMBER: "5432"
       POSTGRESQL_DATA_DIR: "/bitnami/postgresql/data"
       SERVER_NAME: "convy"
       DISCOVERY_SERVICE_HOST: "consul-prod"
       CONSUL_SERVICE_NAME: "postgres-14-repmgr"
       POSTGRESQL_SHARED_PRELOAD_LIBRARIES: "repmgr,pg_stat_statements"
       POSTGRESQL_MAX_CONNECTIONS: "200"
       REPMGR_NODE_PRIORITY: "90"
    volumes:
      - "pg-2_data:/bitnami/postgresql"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 2048000000 # (this means 2GB)
    networks:
      dev_network:
    stop_grace_period: 180s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 1000
        window: 180s
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [ node.labels.pg-2  == true ]
  
volumes:
  pg-1_data:
  pg-2_data:
networks:
  dev_network:
    driver: overlay
    external: true
