version: "3"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    environment:
      - TZ=Europe/London
    volumes:
      - heimdall:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ids
    ports:
      - 8088:80
      - 443:443
    restart: unless-stopped
volumes:
  heimdall: