version: '3.5'
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == retropie
    volumes:
        - home-assistant:/config
    restart: unless-stopped

volumes:
  home-assistant: