version: '3.9'

services:
  php:
    image: php8-local:latest
    depends_on:
        - mariadb
    volumes:
        - '/docker/sc/workdir:/var/www/html'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_SELECTOR}
    networks:
      - db-network

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
        - 80:80
    volumes:
        - '/docker/sc/workdir/usr/share/nginx/html/eInvoice'
        - '/docker/sc/workdir/nginx-config/00-nginx:/etc/nginx/sites-enabled/default'
        - '/docker/sc/workdir/nginx-config/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
        - php
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NGINX_PLACEMENT}
    networks:
      - db-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - 8080:80
    environment:
        PMA_HOST: mariadb
    depends_on:
        - mariadb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_SELECTOR}
    networks:
      - db-network
networks:
  db-network:
    external: true

