version: "3"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - TZ=Europe/London
    volumes:
      - heimdall:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.heimdall-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.heimdall-http.entrypoints=web
          - traefik.http.routers.heimdall-http.middlewares=https-redirect
          - traefik.http.routers.heimdall-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.heimdall-https.entrypoints=websecure
          - traefik.http.routers.heimdall-https.tls=true
          - traefik.http.routers.heimdall-https.tls.certresolver=leresolver
          - traefik.http.services.heimdall.loadbalancer.server.port=80
    #ports:
    #  - 8081:80
    #  - 9443:443
    restart: unless-stopped
volumes:
  heimdall:
