version: "3"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - TZ=Europe/London
    volumes:
      - heimdall:/config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.portainer-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.portainer-http.entrypoints=http
          - traefik.http.routers.portainer-http.middlewares=https-redirect
          - traefik.http.routers.portainer-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.portainer-https.entrypoints=https
          - traefik.http.routers.portainer-https.tls=true
          - traefik.http.routers.portainer-https.tls.certresolver=le
          - traefik.http.services.portainer.loadbalancer.server.port=8081
    ports:
      - 8081:80
      - 443:443
    restart: unless-stopped
volumes:
  heimdall:
