version: "3.7"
services:
  plex_server:
    image: lscr.io/linuxserver/plex:latest
    # container_name: plex-ubuntu
    restart: unless-stopped
    network_mode: "host" 
    privileged: true
    ports:
      - "32400:32400/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
    labels: 
      - traefik.enable=true 
      - traefik.docker.network=traefik-public 
      - traefik.constraint-label=traefik-public 
      - traefik.http.routers.plex-http.rule=Host(`${DOMAIN?Variable not set}`) 
      - traefik.http.routers.plex-http.entrypoints=web 
      - traefik.http.routers.plex-http.middlewares=redirect-to-https 
      - traefik.http.routers.plex-https.rule=Host(`${DOMAIN?Variable not set}`) 
      - traefik.http.routers.plex-https.entrypoints=websecure 
      - traefik.http.routers.plex-https.tls=true 
      - traefik.http.routers.plex-https.tls.certresolver=leresolver 
      - traefik.http.services.plex.loadbalancer.server.port=32400
    networks: 
      - traefik-public 
      #placement:
      #  constraints:
      #    - node.role == worker
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/comedy:/mnt/comedy
      - /docker/plex/movies:/mnt/movies
    restart: unless-stopped
networks:  
   traefik-public:
     external: true
