---
version: "3.8"
services:
  plex_server:
    image: linuxserver/plex
    restart: unless-stopped
    privileged: true
    networks:
      - traefik-public
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == archive-server
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.plex-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.plex-http.entrypoints=web
          - traefik.http.routers.plex-http.middlewares=redirect-to-https
          - traefik.http.routers.plex-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.plex-https.entrypoints=websecure
          - traefik.http.routers.plex-https.tls=true
          - traefik.http.routers.plex-https.tls.certresolver=leresolver
          - traefik.http.services.plex.loadbalancer.server.port=32400
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/comedy:/mnt/comedy
      - /docker/plex/movies:/mnt/movies
networks:
  traefik-public:
    external: true