version: "3.8"
services:
  plex_server:
    image: linuxserver/plex
    restart: unless-stopped
    privileged: true
    ports:
      - "32400:32400/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == archive-server
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/comedy:/mnt/comedy
      - /docker/plex/movies:/mnt/movies
    restart: unless-stopped
