---
version: "3.9"
services:
  plex_server:
    image: linuxserver/plex
    restart: always
    networks:
      - traefik-public
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.Plex == true
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/comedy:/mnt/comedy
      - /docker/plex/movies:/mnt/movies

networks:
  traefik-public:
    external: true