version: '3'
services:
  ubuntu:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-ubuntu
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == portainer-pi3
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/movies:/mnt/movies
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      swarm-macvlan:
        ipv4_address: 192.168.1.241

networks:
  swarm-macvlan:
    external: true