version: '3'
services:
  ubuntu:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex-ubuntu
    restart: unless-stopped
    privileged: true
    ports:
      - "32400:32400/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == portainer-pi3
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/movies:/mnt/movies
    restart: unless-stopped