version: '3'
services:
  plex_server:
    image: lscr.io/linuxserver/plex:latest
    # container_name: plex-ubuntu
    restart: unless-stopped
    network_mode: "host" 
    privileged: true
    ports:
      - "32400:32400/tcp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      #placement:
      #  constraints:
      #    - node.role == worker
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tv:/mnt/tv
      - /docker/plex/comedy:/mnt/comedy
      - /docker/plex/movies:/mnt/movies
    restart: unless-stopped
