groups:
- name: Raspberry Cluster
  rules:

  - alert: service_down
    expr: up == 0
    for: 5m
    labels:
      severity: critical
      quiethours: budapest
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."

  - alert: medium_load
    expr: node_load1 > 1.5
    for: 10m
    labels:
      severity: warning
      quiethours: budapest
    annotations:
      summary: "Instance {{ $labels.instance }} running on server {{ $labels._hostname }} under medium load"
      description: "The Server: {{ $labels._hostname }}'s exporter named {{ $labels.job }} is under medium load."

  - alert: high_load
    expr: node_load1 > 3.0
    for: 30m
    labels:
      severity: critical
      quiethours: budapest
    annotations:
      summary: "Instance {{ $labels.instance }} running on server {{ $labels._hostname }} under high load"
      description: "The Server: {{ $labels.instance }}'s exporter named {{ $labels.job }} is under high load."

  - alert: site_down
    expr: probe_success < 1
    for: 30s
    labels:
      severity: warning
      quiethours: budapest
    annotations:
      summary: "Site Down: {{$labels.instance}}"
      description: "Site Down: {{$labels.instance}} for more than 30 seconds"

  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
      quiethours: budapest
    annotations:
      summary: Host out of disk space (instance {{ $labels.instance }})
      description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 2m
    labels:
      severity: warning
      quiethours: budapest
    annotations:
      summary: Host out of memory (instance {{ $labels.instance }})
      description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
