---
version: '3.7'
services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - "GF_SECURITY_ADMIN_USER=${ADMIN_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PW}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /docker/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /docker/monitoring/grafana/provisioning/:/etc/grafana/provisioning
      - /docker/monitoring/grafana/dashboards/:/var/lib/grafana/dashboards
    networks:
      - consul-bridge
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: ${USER_UID}
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/prometheus_data:/prometheus/data
    networks:
      - consul-bridge
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - /docker/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    networks:
      - consul-bridge
networks:
  consul-bridge:
    external: true

