---
version: '3.7'
services:

  grafana:
    image: grafana/grafana:7.5.3
    container_name: grafana
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /docker/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /docker/monitoring/grafana/provisioning/:/etc/grafana/provisioning
      - /docker/monitoring/grafana/dashboards/:/var/lib/grafana/dashboards
    networks:
      - bridge
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bridge
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - bridge
    ports:
      - 9100:9100

networks:
  bridge:
    external: true
