---
version: '3.7'
services:

  grafana:
    image: grafana/grafana:7.5.3
    container_name: grafana
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /docker/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /docker/monitoring/grafana/provisioning/:/etc/grafana/provisioning
      - /docker/monitoring/grafana/dashboards/:/var/lib/grafana/dashboards
    networks:
      - consul-bridge
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    volumes:
      - /docker/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/data
    networks:
      - consul-bridge
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

networks:
  consul-bridge:
    external: true
    
volumes:
  prometheus_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: "/docker/monitoring/prometheus/data"
