---
version: '3.8'
services:

  mysqld-exporter:
    image: prom/mysqld-exporter
    restart: always
    ports:
      - 9104:9104
    command: --mysqld.username=exporter
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
    networks:
      - consul-bridge
      - db-network
    volumes:
      - /docker/monitoring/my.cnf:/home/.my.cnf
networks:
  consul-bridge:
    external: true
  db-network:
    external: true