---
version: '3.8'
services:

  mysqld-exporter:
    image: prom/mysqld-exporter
    restart: always
    ports:
      - 9104:9104
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
    networks:
      - consul-bridge
networks:
  consul-bridge:
    external: true