---
version: '3.8'
services:

  nextcloud-exporter:
    image: ghcr.io/xperimental/nextcloud-exporter
    restart: always
    ports:
      - 9205:9205
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
    networks:
      - consul-bridge
networks:
  consul-bridge:
    external: true
