---
version: '3.8'
services:

  nextcloud-exporter:
    image: ghcr.io/xperimental/nextcloud-exporter
    restart: always
    environment:
      NEXTCLOUD_SERVER: ${NEXTCLOUD_SERVER}
      NEXTCLOUD_USERNAME: ${NEXTCLOUD_USERNAME}
      NEXTCLOUD_PASSWORD: ${NEXTCLOUD_PASSWORD}
      NEXTCLOUD_TLS_SKIP_VERIFY: ${NEXTCLOUD_TLS_SKIP_VERIFY}
      NEXTCLOUD_AUTH_TOKEN: ${NEXTCLOUD_TOKEN}
    ports:
      - 9205:9205
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
    networks:
      - consul-bridge
networks:
  consul-bridge:
    external: true
