---
version: '3.8'
services:

  nextcloud-exporter:
    image: ghcr.io/xperimental/nextcloud-exporter
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
    volumes:
      - /docker/monitoring/nextcloud-exporter-config.yaml:/home/nextcloud-exporter-config.yaml
    command: 
      - '-c /home/nextcloud-exporter-config.yaml'
    networks:
      - consul-bridge
networks:
  consul-bridge:
    external: true
