version: "3"

services:
  pihole:
    image: pihole/pihole:v5.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Budapest'
      WEBPASSWORD: ${web_password}
    volumes:
      - 'pihole_pihole-etc:/etc/pihole'
      - 'pihole_dnsmasq:/etc/dnsmasq.d'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == retropie
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      swarm-macvlan:
        ipv4_address: 192.168.1.241
    
volumes:
  pihole_pihole-etc:
  pihole_dnsmasq:

networks:
  swarm-macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1