---
version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - db-network
      - traefik-public
    links:
      - mariadb
    volumes:
      - /docker/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD="VN*_JfeD9t-cJiUQXL-^2.Q7"
      - MYSQL_DATABASE="nextcloud"
      - MYSQL_USER=peterb
      - MYSQL_HOST=mariadb
    deploy:
      mode: replicated
      replicas: 1
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.peterbacsai.com`)
          - traefik.http.routers.nextcloud-http.entrypoints=web
          - traefik.http.routers.nextcloud-http.middlewares=redirect-to-https
          - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.peterbacsai.com`)
          - traefik.http.routers.nextcloud-https.entrypoints=websecure
          - traefik.http.routers.nextcloud-https.tls=true
          - traefik.http.routers.nextcloud-https.tls.certresolver=leresolver
          - traefik.http.services.nextcloud.loadbalancer.server.port=80
    restart: unless-stopped

networks:
  db-network:
    external: true
  traefik-public:
    external: true
