---
version: '3.8'

services:

  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_PASSWORD=${MYSQL_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
    restart: unless-stopped
    
  mariadb-exporter:
    image: quay.io/prometheus/mysqld-exporter
    command:
     - -collect.info_schema.tablestats
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME='${MYSQL_USER}:${MYSQL_PW}@(mariadb:3306)/'
    ports:
      - 9104:9104
    networks:
      - nextcloud_network
      - consul-bridge
    depends_on:
      - mariadb

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
      - traefik-public
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=${MYSQL_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.nextcloud-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.nextcloud-http.entrypoints=web
          - traefik.http.routers.nextcloud-http.middlewares=redirect-to-https
          - traefik.http.routers.nextcloud-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.nextcloud-https.entrypoints=websecure
          - traefik.http.routers.nextcloud-https.tls=true
          - traefik.http.routers.nextcloud-https.tls.certresolver=leresolver
          - traefik.http.services.nextcloud.loadbalancer.server.port=80
    restart: unless-stopped
volumes:
  nextcloud:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/nextcloud"
  db:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/mariadb"

networks:
  nextcloud_network:
  traefik-public:
    external: true
  consul-bridge:
    external: true
