---
version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - db-network
      - traefik-public
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=${MYSQL_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.nextcloud-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.nextcloud-http.entrypoints=web
          - traefik.http.routers.nextcloud-http.middlewares=redirect-to-https
          - traefik.http.routers.nextcloud-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.nextcloud-https.entrypoints=websecure
          - traefik.http.routers.nextcloud-https.tls=true
          - traefik.http.routers.nextcloud-https.tls.certresolver=leresolver
          - traefik.http.services.nextcloud.loadbalancer.server.port=80
    restart: unless-stopped
volumes:
  nextcloud:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/nextcloud"
  db:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/mariadb"

networks:
  db-network:
    external: true
  traefik-public:
    external: true
