version: '3.8'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    networks:
      - bridge
      - traefik-public
    expose:
      - 8123
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - STARTUP=${startup?Startup variable not set} 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
    volumes:
        - /docker/home-assistant:/config
    restart: unless-stopped

networks:
  bridge:
    external: true
  traefik-public:
    external: true