version: '3.8'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    networks:
      - traefik-public
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - 8123:8123
    # security_opt:
    #   - seccomp:unconfined
    #   - apparmor:unconfined
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - STARTUP=${startup?Startup variable not set} 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker
      labels:
          - traefik.enable=true
          - traefik.http.routers.home-assistant-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.home-assistant-http.entrypoints=web
          - traefik.http.routers.home-assistant-http.middlewares=redirect-to-https
          - traefik.http.routers.home-assistant-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.home-assistant-https.entrypoints=websecure
          - traefik.http.routers.home-assistant-https.tls=true
          - traefik.http.routers.home-assistant-https.tls.certresolver=leresolver
          - traefik.http.services.home-assistant.loadbalancer.server.port=8123
    volumes:
        - /docker/home-assistant:/config
    restart: unless-stopped

networks:
  traefik-public:
    external: true