version: '3.4'
services:
  isc-dhcp-server:
    image: isc-dhcp-server:latest
    container_name: isc-dhcp-server
    restart: always
    environment:
      - use_data_dir=true
      - data_dir=/data
      - IFACE=eth0
      - swarm=true
    privileged: true
    volumes:
      - '/docker/dhcp:/data'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
networks:
  outside:
    external:
      name: "host"
