version: '3.4'
services:
  isc-dhcp-server-primary:
    image: isc-dhcp-server:latest
    container_name: isc-dhcp-server
    restart: always
    environment:
      - use_data_dir=true
      - data_dir=/data
      - IFACE=eth0
      - swarm=true
    privileged: true
    volumes:
      - '/docker/isc-dhcp-ha/dhcpd-master.conf:/data/dhcpd.conf'
      #- '/docker/dhcp/dhcpd.leases:/etc/dhcp/dhcpd.leases'
      #- '/docker/dhcp/dhcpd.hosts:/etc/dhcp/dhcpd.hosts'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${PRIMARY_NODE}
  isc-dhcp-server-secondary:
    image: isc-dhcp-server:latest
    container_name: isc-dhcp-server
    restart: always
    environment:
      - use_data_dir=true
      - data_dir=/data
      - IFACE=eth0
      - swarm=true
    privileged: true
    volumes:
      - '/docker/isc-dhcp-ha/dhcpd-worker.conf:/data/dhcpd.conf'
      #- '/docker/isc-dhcp-ha/dhcpd.leases:/etc/dhcp/dhcpd.leases'
      #- '/docker/isc-dhcp-ha/dhcpd.hosts:/etc/dhcp/dhcpd.hosts'
    networks:
      - outside
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${SECONDARY_NODE}
networks:
  outside:
    external:
      name: "host"
