version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
      #labels:
      #    - traefik.enable=true
      #    - traefik.docker.network=traefik-public
      #    - traefik.constraint-label=traefik-public
      #    - traefik.http.routers.consul.rule=Host(`${DOMAIN?Variable not set}`)
      #    - traefik.http.routers.consul.entrypoints=web
      #    - traefik.http.routers.consul.middlewares=redirect-to-https
      #    - traefik.http.routers.consuls.rule=Host(`${DOMAIN?Variable not set}`)
      #    - traefik.http.routers.consuls.entrypoints=websecure
      #    - traefik.http.routers.consuls.tls=true
      #    - traefik.http.routers.consuls.tls.certresolver=leresolver
      #    - traefik.http.services.consul.loadbalancer.server.port=8500
    restart: always
    volumes:
     - /docker/consul/server:/consul
    networks:
      - bridge
      #- traefik-public
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${CLIENT_NODENAME}
    restart: always
    volumes:
     - /docker/consul/client:/consul
    networks:
      - bridge
    command: "agent"

#volumes:
#  consul_nfs_server:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NFS_HOST},nfsvers=4"
#      device: ":/docker/consul/server"
#  consul_nfs_client:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NFS_HOST},nfsvers=4"
#      device: ":/docker/consul/client"
      
networks:
  bridge:
  #traefik-public:
  #  external: true
  
