version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    restart: always
    volumes:
     - /docker/consul/server:/consul
    networks:
      - consul-bridge
      #- traefik-public
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE1}
    restart: always
    volumes:
     - /docker/consul/client/config/client.json:/consul/config/client.json
    networks:
      - consul-bridge
    command: "agent"
 
  consul-client1:
    image: hashicorp/consul:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE2}
    restart: always
    volumes:
     - /docker/consul/client/config/client1.json:/consul/config/client.json
    networks:
      - consul-bridge
    command: ["agent", "-node=master-1"]

#volumes:
#  consul_nfs_server:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NFS_HOST},nfsvers=4"
#      device: ":/docker/consul/server"
#  consul_nfs_client:
#    driver_opts:
#      type: "nfs"
#      o: "addr=${NFS_HOST},nfsvers=4"
#      device: ":/docker/consul/client"
      
networks:
  consul-bridge:
     external: true
