version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}
    restart: always
    volumes:
     - consul_nfs:/consul
    networks:
      - bridge
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: ["agent", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]

  consul-client:
    image: hashicorp/consul:1.10.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${CLIENT_NODENAME}
    restart: always
    volumes:
     - consul_nfs:/consul
    networks:
      - bridge
    command: "agent"

volumes:
  consul_nfs:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/consul"
      
networks:
  bridge:
