version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:latest
    environment:
      - PUID=1000
      - PGID=1000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.Consul == true
      labels:
          - traefik.enable=true
          - traefik.http.routers.consul-http.rule=Host(`${CONSUL_DOMAIN?Variable not set}`)
          - traefik.http.routers.consul-http.entrypoints=web
          - traefik.http.routers.consul-http.middlewares=redirect-to-https
          - traefik.http.routers.consul-https.rule=Host(`${CONSUL_DOMAIN?Variable not set}`)
          - traefik.http.routers.consul-https.entrypoints=websecure
          - traefik.http.routers.consul-https.middlewares=authconsul
          - traefik.http.middlewares.authconsul.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
          - traefik.http.routers.consul-https.tls=true
          - traefik.http.routers.consul-https.tls.certresolver=leresolver
          - traefik.http.services.consul.loadbalancer.server.port=8500
    restart: always
    volumes:
     - /docker/consul/server:/consul
     - /docker/consul/server/data:/consul/data
    networks:
      - consul-bridge
      - traefik-public
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE1}
    restart: always
    volumes:
      - /docker/consul/client/${NODE1}:/consul/config
    networks:
      - consul-bridge
    command: ["agent", "-node=${NODE1}", "-config-file=/consul/config/${NODE1}.json"]
 
  consul-client1:
    image: hashicorp/consul:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.Consulclient == true
    restart: always
    volumes:
      - /docker/consul/client/${NODE2}:/consul/config
    networks:
      - consul-bridge
    command: ["agent", "-node=${NODE2}", "-config-file=/consul/config/${NODE2}.json"]

volumes:
  consul_nfs_server:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/consul/server"
  consul_nfs_client:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/consul/client"
      
networks:
  consul-bridge:
    external: true
  traefik-public:
    external: true
