---
version: '3.8'

services:
  web:
    image: nginx
    networks:
      - traefik-public
    ports:
      - 8089:80
    volumes:
     - templates:/etc/nginx/templates
     - src:/usr/share/nginx/html
     - conf=nginx.conf:/etc/nginx/nginx.conf
    environment:
     - NGINX_HOST=${DOMAIN?Variable not set}
     - NGINX_PORT=80
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODESELECTOR}
      labels:
          - traefik.enable=true
          - traefik.http.routers.nginx-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.nginx-http.entrypoints=web
          - traefik.http.routers.nginx-http.middlewares=redirect-to-https
          - traefik.http.routers.nginx-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.nginx-https.entrypoints=websecure
          #- traefik.http.routers.nginx-https.middlewares=authnginx
          #- traefik.http.middlewares.authnginx.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
          - traefik.http.routers.nginx-https.tls=true
          - traefik.http.routers.nginx-https.tls.certresolver=leresolver
          - traefik.http.services.nginx.loadbalancer.server.port=80
volumes:
  src:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/nginx/src"
  templates:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_HOST},nfsvers=4"
      device: ":/docker/nginx/templates"

networks:
  traefik-public:
    external: true
