global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/rules.d/*.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'consul-server'
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['consul-server:8500']
  - job_name: windows-exporter
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
    - server: consul-server:8500
      services: [windows-exporter]
    relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app
    - source_labels: [__meta_consul_tags]
      regex: .*,_service=([^,]+),.*
      replacement: ${1}
      target_label: _service
    - source_labels: [__meta_consul_tags]
      regex: .*,_hostname=([^,]+),.*
      replacement: ${1}
      target_label: _hostname
    - source_labels: [__meta_consul_tags]
      regex: .*,_environment=([^,]+),.*
      replacement: ${1}
      target_label: _environment
    - source_labels: [__meta_consul_tags]
      regex: .*,_cluster=([^,]+),.*
      replacement: ${1}
      target_label: _cluster
    - source_labels: [__meta_consul_tags]
      regex: .*,_es_role=([^,]+),.*
      replacement: ${1}
      target_label: _es_role
  - job_name: node-exporter
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
    - server: consul-server:8500
      services: [node-exporter]
    relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app
    - source_labels: [__meta_consul_tags]
      regex: .*,_service=([^,]+),.*
      replacement: ${1}
      target_label: _service
    - source_labels: [__meta_consul_tags]
      regex: .*,_hostname=([^,]+),.*
      replacement: ${1}
      target_label: _hostname
    - source_labels: [__meta_consul_tags]
      regex: .*,_environment=([^,]+),.*
      replacement: ${1}
      target_label: _environment
    - source_labels: [__meta_consul_tags]
      regex: .*,_cluster=([^,]+),.*
      replacement: ${1}
      target_label: _cluster
    - source_labels: [__meta_consul_tags]
      regex: .*,_es_role=([^,]+),.*
      replacement: ${1}
      target_label: _es_role
  - job_name: mariadb-metrics
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
    - server: consul-server:8500
      services: [mariadb-metrics]
    relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app
    - source_labels: [__meta_consul_tags]
      regex: .*,_service=([^,]+),.*
      replacement: ${1}
      target_label: _service
    - source_labels: [__meta_consul_tags]
      regex: .*,_hostname=([^,]+),.*
      replacement: ${1}
      target_label: _hostname
    - source_labels: [__meta_consul_tags]
      regex: .*,_environment=([^,]+),.*
      replacement: ${1}
      target_label: _environment
    - source_labels: [__meta_consul_tags]
      regex: .*,_cluster=([^,]+),.*
      replacement: ${1}
      target_label: _cluster
    - source_labels: [__meta_consul_tags]
      regex: .*,_es_role=([^,]+),.*
      replacement: ${1}
      target_label: _es_role
  - job_name: nextcloud-exporter
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
    - server: consul-server:8500
      services: [nextcloud-exporter]
    relabel_configs:
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app
    - source_labels: [__meta_consul_tags]
      regex: .*,_service=([^,]+),.*
      replacement: ${1}
      target_label: _service
    - source_labels: [__meta_consul_tags]
      regex: .*,_hostname=([^,]+),.*
      replacement: ${1}
      target_label: _hostname
    - source_labels: [__meta_consul_tags]
      regex: .*,_environment=([^,]+),.*
      replacement: ${1}
      target_label: _environment
    - source_labels: [__meta_consul_tags]
      regex: .*,_cluster=([^,]+),.*
      replacement: ${1}
      target_label: _cluster
    - source_labels: [__meta_consul_tags]
      regex: .*,_es_role=([^,]+),.*
      replacement: ${1}
      target_label: _es_role
  - job_name: mysqld-metrics
    static_configs:
      - targets:
        - mariadb:3306
        - mariadb-slave:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld-exporter:9104
