---
version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    networks:
      - vault-network
      - consul-bridge
    restart: on-failure:10
    ports:
      - 8201:8201
      - 8200:8200
    environment:
      VAULT_API_ADDR: "https://vault:8201"
      VAULT_ADDRESS: "http://vault:8200"
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: ${VAULT_TOKEN}
      SECRETS_PATH: kv/data/
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config
    volumes:
      - /docker/vault/vault-backend:/vault/file
      - /docker/vault/vault-logs:/vault/logs
      - /docker/vault/configs:/vault/config:ro
      - /docker/vault/certs/server.crt:/etc/vault/server.crt
      - /docker/vault/certs/server.key:/etc/vault/server.key
      - /docker/vault/plugins:/vault/plugins
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODESELECTOR}
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.vault.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.vault.entrypoints=web
        - traefik.http.routers.vault.middlewares=redirect-to-https
        - traefik.http.routers.vault-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.vault-https.entrypoints=websecure
        - traefik.http.routers.vault-https.tls=true
        - traefik.http.routers.vault-https.tls.certresolver=leresolver
        - traefik.http.services.vault.loadbalancer.server.port=80

networks:
  vault-network:
    external: true
  consul-bridge:
    external: true
