---
version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    networks:
      - vault-network
      - consul-bridge
    restart: on-failure:10
    ports:
      - 8201:8201
      - 8200:8200
    environment:
      VAULT_API_ADDR: "https://vault:8201"
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"0", "tls_cert_file":"/etc/vault/server.crt", "tls_key_file":"/etc/vault/server.key"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: ${VAULT_TOKEN}
    cap_add:
      - IPC_LOCK
    volumes:
      - /docker/vault/vault-backend:/vault/file
      - /docker/vault/vault-logs:/vault/logs
      - /docker/vault/configs:/vault/config
      - /docker/vault/certs/server.crt:/etc/vault/server.crt
      - /docker/vault/certs/server.key:/etc/vault/server.key
      - /docker/vault/plugins:/vault/plugins
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODESELECTOR}

networks:
  vault-network:
    external: true
  consul-bridge:
    external: true
