version: "3.3"
services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      password: ${password}
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.portainer-http.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.portainer-http.entrypoints=web
          - traefik.http.routers.portainer-http.middlewares=https-redirect
          - traefik.http.routers.portainer-https.rule=Host(`${DOMAIN?Variable not set}`)
          - traefik.http.routers.portainer-https.entrypoints=websecure
          - traefik.http.routers.portainer-https.tls=true
          - traefik.http.routers.portainer-https.tls.certresolver=leresolver
          - traefik.http.services.portainer.loadbalancer.server.port=9000
networks:
  agent-network:
    attachable: true
  traefik-public:
    external: true
volumes:
  portainer_data:
