version: "3.5"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    network_mode: "host" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - TRANSMISSION_WEB_HOME=/transmissionic/
      - USER=${admin_user} 
      - PASS=/run/secrets/transmission-password
    ports:
      - "9091:9091/tcp"
      - "51413:51413"
      - "51413:51413/udp"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == portainer-pi3
    restart: unless-stopped
    volumes:
      - /docker/transmission:/downloads
      - /docker/plex/movies:/movies
      - transmission-config:/config
    secrets:
      - transmission-password
  secrets:
    transmission-password:
      external: true
volumes:
  transmission-config:
