version: "3.1"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    network_mode: "host" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - STARTUP=${startup?Startup variable not set} 
      - USER=${admin_user} 
      - PASS=${admin_password}
    ports:
      - "${external_port}:9091/tcp"
      - "${secondary_external_port}:51413"
      - "${secondary_external_port}:51413/udp"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${host}
    restart: unless-stopped
    volumes:
      - ${download_dir}:/downloads
      - ${config_dir}:/config

volumes:
  transmission-config:
